name: Fully complete build and upload to Test PyPI workflow

# "on" specifies the workflow trigger.
# Automatic trigger which will be activated on a pushed commit which has a tag
# attached to it with a name starting with "v".
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initial echo
        run: echo "Initialize"

      # NOTE: We are using particular commits of all actions to achieve
      # reproducibility.

      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      # NOTE: Use the same python version here as the one you have chosen locally
      # in your virtual environment. This is important for reproducibility.
      - name: Set up Python
        uses: actions/setup-python@c4e89fac7e8767b327bbad6cb4d859eda999cf08
        with:
          python-version: '3.9'

      - name: Install build dependency
        run: python3 -m pip install -r requirements-build.txt

      - name: Build
        run: python3 -m build

      # We are listing sha256 sums of the build files to make sure that what was
      # built on GitHub matches what was built locally.
      - name: List shas
        run: sha256sum dist/*

      # Takes the "dist" directory and stores it as "build-artifacts", so that
      # in the next job we can access those files. Pass data between 2 steps.
      - name: Store build artifacts
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: build-artifacts
          path: dist

  upload:
    runs-on: ubuntu-latest
    needs: build
    environment: release
    steps:
      - name: Download artifacts from "build-artifacts"
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: build-artifacts
          path: dist

      - name: Publish binary wheel and source tarball on PyPI
        uses: pypa/gh-action-pypi-publish@717ba43cfbb0387f6ce311b169a825772f54d295
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
