name: GitHub release workflow example

# "on" specifies the workflow trigger.
on:
  # "workflow_dispatch" means that a manual trigger is required to run this workflow
  workflow_dispatch:

jobs:
  build: # name of that particular step in the job, it could be a custom string
    runs-on: ubuntu-latest
    steps:
      - name: Initial echo
        run: echo "Initialize" # command that will be run when executing this step.

      # NOTE: We are using particular commits of all actions to achieve reproducibility.

      # The runner doesn't have your code if you don't checkout
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Set up Python
        uses: actions/setup-python@c4e89fac7e8767b327bbad6cb4d859eda999cf08
        with:
        # NOTE: Use the same python version here as the one you have chosen locally
        # in your virtual environment. This is important for reproducibility.
          python-version: '3.9'

      - name: Install build dependency
        run: python3 -m pip install build

      - name: Build
        run: python3 -m build

      # We are listing sha256 sums of the build files to make sure that what was
      # built on GitHub matches what was built locally.
      - name: List shas
        run: sha256sum dist/*

      # Takes the "dist" directory and stores it as "build-artifacts", so that
      # in the next job we can access those files. Pass data between 2 steps.
      - name: Store build artifacts
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: build-artifacts # name in a database
          path: dist

  upload:
    runs-on: ubuntu-latest
    needs: build
    environment: release
    steps:
      # Download build artifacts from the "build-artifacts" directory.
      - name: Fetch build artifacts
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: build-artifacts
          path: dist # this is the output directory

      # This action is not officially released by GitHub in a contrast to all others.
      # The reason is that the GitHub official action alternative is not well supported.
      - name: Publish binary wheel and source tarball on PyPI
        uses: pypa/gh-action-pypi-publish@717ba43cfbb0387f6ce311b169a825772f54d295
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
